// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.7
// source: api/EventService.proto

package event

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CalendarClient is the client API for Calendar service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CalendarClient interface {
	CreateEventV1(ctx context.Context, in *EventV1, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UpdateEventV1(ctx context.Context, in *EventV1, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeleteEventV1(ctx context.Context, in *EventIdV1, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListEventDayV1(ctx context.Context, in *timestamppb.Timestamp, opts ...grpc.CallOption) (*EventResponseV1, error)
	ListEventWeekV1(ctx context.Context, in *timestamppb.Timestamp, opts ...grpc.CallOption) (*EventResponseV1, error)
	ListEventMonthV1(ctx context.Context, in *timestamppb.Timestamp, opts ...grpc.CallOption) (*EventResponseV1, error)
}

type calendarClient struct {
	cc grpc.ClientConnInterface
}

func NewCalendarClient(cc grpc.ClientConnInterface) CalendarClient {
	return &calendarClient{cc}
}

func (c *calendarClient) CreateEventV1(ctx context.Context, in *EventV1, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/Calendar/CreateEventV1", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calendarClient) UpdateEventV1(ctx context.Context, in *EventV1, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/Calendar/UpdateEventV1", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calendarClient) DeleteEventV1(ctx context.Context, in *EventIdV1, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/Calendar/DeleteEventV1", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calendarClient) ListEventDayV1(ctx context.Context, in *timestamppb.Timestamp, opts ...grpc.CallOption) (*EventResponseV1, error) {
	out := new(EventResponseV1)
	err := c.cc.Invoke(ctx, "/Calendar/ListEventDayV1", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calendarClient) ListEventWeekV1(ctx context.Context, in *timestamppb.Timestamp, opts ...grpc.CallOption) (*EventResponseV1, error) {
	out := new(EventResponseV1)
	err := c.cc.Invoke(ctx, "/Calendar/ListEventWeekV1", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calendarClient) ListEventMonthV1(ctx context.Context, in *timestamppb.Timestamp, opts ...grpc.CallOption) (*EventResponseV1, error) {
	out := new(EventResponseV1)
	err := c.cc.Invoke(ctx, "/Calendar/ListEventMonthV1", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CalendarServer is the server API for Calendar service.
// All implementations must embed UnimplementedCalendarServer
// for forward compatibility
type CalendarServer interface {
	CreateEventV1(context.Context, *EventV1) (*emptypb.Empty, error)
	UpdateEventV1(context.Context, *EventV1) (*emptypb.Empty, error)
	DeleteEventV1(context.Context, *EventIdV1) (*emptypb.Empty, error)
	ListEventDayV1(context.Context, *timestamppb.Timestamp) (*EventResponseV1, error)
	ListEventWeekV1(context.Context, *timestamppb.Timestamp) (*EventResponseV1, error)
	ListEventMonthV1(context.Context, *timestamppb.Timestamp) (*EventResponseV1, error)
	mustEmbedUnimplementedCalendarServer()
}

// UnimplementedCalendarServer must be embedded to have forward compatible implementations.
type UnimplementedCalendarServer struct {
}

func (UnimplementedCalendarServer) CreateEventV1(context.Context, *EventV1) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateEventV1 not implemented")
}
func (UnimplementedCalendarServer) UpdateEventV1(context.Context, *EventV1) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateEventV1 not implemented")
}
func (UnimplementedCalendarServer) DeleteEventV1(context.Context, *EventIdV1) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteEventV1 not implemented")
}
func (UnimplementedCalendarServer) ListEventDayV1(context.Context, *timestamppb.Timestamp) (*EventResponseV1, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListEventDayV1 not implemented")
}
func (UnimplementedCalendarServer) ListEventWeekV1(context.Context, *timestamppb.Timestamp) (*EventResponseV1, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListEventWeekV1 not implemented")
}
func (UnimplementedCalendarServer) ListEventMonthV1(context.Context, *timestamppb.Timestamp) (*EventResponseV1, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListEventMonthV1 not implemented")
}
func (UnimplementedCalendarServer) mustEmbedUnimplementedCalendarServer() {}

// UnsafeCalendarServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CalendarServer will
// result in compilation errors.
type UnsafeCalendarServer interface {
	mustEmbedUnimplementedCalendarServer()
}

func RegisterCalendarServer(s grpc.ServiceRegistrar, srv CalendarServer) {
	s.RegisterService(&Calendar_ServiceDesc, srv)
}

func _Calendar_CreateEventV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventV1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarServer).CreateEventV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Calendar/CreateEventV1",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarServer).CreateEventV1(ctx, req.(*EventV1))
	}
	return interceptor(ctx, in, info, handler)
}

func _Calendar_UpdateEventV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventV1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarServer).UpdateEventV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Calendar/UpdateEventV1",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarServer).UpdateEventV1(ctx, req.(*EventV1))
	}
	return interceptor(ctx, in, info, handler)
}

func _Calendar_DeleteEventV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventIdV1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarServer).DeleteEventV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Calendar/DeleteEventV1",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarServer).DeleteEventV1(ctx, req.(*EventIdV1))
	}
	return interceptor(ctx, in, info, handler)
}

func _Calendar_ListEventDayV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(timestamppb.Timestamp)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarServer).ListEventDayV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Calendar/ListEventDayV1",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarServer).ListEventDayV1(ctx, req.(*timestamppb.Timestamp))
	}
	return interceptor(ctx, in, info, handler)
}

func _Calendar_ListEventWeekV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(timestamppb.Timestamp)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarServer).ListEventWeekV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Calendar/ListEventWeekV1",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarServer).ListEventWeekV1(ctx, req.(*timestamppb.Timestamp))
	}
	return interceptor(ctx, in, info, handler)
}

func _Calendar_ListEventMonthV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(timestamppb.Timestamp)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarServer).ListEventMonthV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Calendar/ListEventMonthV1",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarServer).ListEventMonthV1(ctx, req.(*timestamppb.Timestamp))
	}
	return interceptor(ctx, in, info, handler)
}

// Calendar_ServiceDesc is the grpc.ServiceDesc for Calendar service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Calendar_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Calendar",
	HandlerType: (*CalendarServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateEventV1",
			Handler:    _Calendar_CreateEventV1_Handler,
		},
		{
			MethodName: "UpdateEventV1",
			Handler:    _Calendar_UpdateEventV1_Handler,
		},
		{
			MethodName: "DeleteEventV1",
			Handler:    _Calendar_DeleteEventV1_Handler,
		},
		{
			MethodName: "ListEventDayV1",
			Handler:    _Calendar_ListEventDayV1_Handler,
		},
		{
			MethodName: "ListEventWeekV1",
			Handler:    _Calendar_ListEventWeekV1_Handler,
		},
		{
			MethodName: "ListEventMonthV1",
			Handler:    _Calendar_ListEventMonthV1_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/EventService.proto",
}
