// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: EventService.proto

package internalgrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CalendarClient is the client API for Calendar service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CalendarClient interface {
	CreateEventV1(ctx context.Context, in *EventV1, opts ...grpc.CallOption) (*ResponseStatusV1, error)
	UpdateEventV1(ctx context.Context, in *EventV1, opts ...grpc.CallOption) (*ResponseStatusV1, error)
	DeleteEventV1(ctx context.Context, in *EventIdV1, opts ...grpc.CallOption) (*ResponseStatusV1, error)
	ListEventsDayV1(ctx context.Context, in *EventListRequestV1, opts ...grpc.CallOption) (*EventResponseV1, error)
	ListEventsWeekV1(ctx context.Context, in *EventListRequestV1, opts ...grpc.CallOption) (*EventResponseV1, error)
	ListEventsMonthV1(ctx context.Context, in *EventListRequestV1, opts ...grpc.CallOption) (*EventResponseV1, error)
}

type calendarClient struct {
	cc grpc.ClientConnInterface
}

func NewCalendarClient(cc grpc.ClientConnInterface) CalendarClient {
	return &calendarClient{cc}
}

func (c *calendarClient) CreateEventV1(ctx context.Context, in *EventV1, opts ...grpc.CallOption) (*ResponseStatusV1, error) {
	out := new(ResponseStatusV1)
	err := c.cc.Invoke(ctx, "/Calendar/CreateEventV1", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calendarClient) UpdateEventV1(ctx context.Context, in *EventV1, opts ...grpc.CallOption) (*ResponseStatusV1, error) {
	out := new(ResponseStatusV1)
	err := c.cc.Invoke(ctx, "/Calendar/UpdateEventV1", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calendarClient) DeleteEventV1(ctx context.Context, in *EventIdV1, opts ...grpc.CallOption) (*ResponseStatusV1, error) {
	out := new(ResponseStatusV1)
	err := c.cc.Invoke(ctx, "/Calendar/DeleteEventV1", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calendarClient) ListEventsDayV1(ctx context.Context, in *EventListRequestV1, opts ...grpc.CallOption) (*EventResponseV1, error) {
	out := new(EventResponseV1)
	err := c.cc.Invoke(ctx, "/Calendar/ListEventsDayV1", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calendarClient) ListEventsWeekV1(ctx context.Context, in *EventListRequestV1, opts ...grpc.CallOption) (*EventResponseV1, error) {
	out := new(EventResponseV1)
	err := c.cc.Invoke(ctx, "/Calendar/ListEventsWeekV1", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calendarClient) ListEventsMonthV1(ctx context.Context, in *EventListRequestV1, opts ...grpc.CallOption) (*EventResponseV1, error) {
	out := new(EventResponseV1)
	err := c.cc.Invoke(ctx, "/Calendar/ListEventsMonthV1", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CalendarServer is the server API for Calendar service.
// All implementations must embed UnimplementedCalendarServer
// for forward compatibility
type CalendarServer interface {
	CreateEventV1(context.Context, *EventV1) (*ResponseStatusV1, error)
	UpdateEventV1(context.Context, *EventV1) (*ResponseStatusV1, error)
	DeleteEventV1(context.Context, *EventIdV1) (*ResponseStatusV1, error)
	ListEventsDayV1(context.Context, *EventListRequestV1) (*EventResponseV1, error)
	ListEventsWeekV1(context.Context, *EventListRequestV1) (*EventResponseV1, error)
	ListEventsMonthV1(context.Context, *EventListRequestV1) (*EventResponseV1, error)
	mustEmbedUnimplementedCalendarServer()
}

// UnimplementedCalendarServer must be embedded to have forward compatible implementations.
type UnimplementedCalendarServer struct {
}

func (UnimplementedCalendarServer) CreateEventV1(context.Context, *EventV1) (*ResponseStatusV1, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateEventV1 not implemented")
}
func (UnimplementedCalendarServer) UpdateEventV1(context.Context, *EventV1) (*ResponseStatusV1, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateEventV1 not implemented")
}
func (UnimplementedCalendarServer) DeleteEventV1(context.Context, *EventIdV1) (*ResponseStatusV1, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteEventV1 not implemented")
}
func (UnimplementedCalendarServer) ListEventsDayV1(context.Context, *EventListRequestV1) (*EventResponseV1, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListEventsDayV1 not implemented")
}
func (UnimplementedCalendarServer) ListEventsWeekV1(context.Context, *EventListRequestV1) (*EventResponseV1, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListEventsWeekV1 not implemented")
}
func (UnimplementedCalendarServer) ListEventsMonthV1(context.Context, *EventListRequestV1) (*EventResponseV1, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListEventsMonthV1 not implemented")
}
func (UnimplementedCalendarServer) mustEmbedUnimplementedCalendarServer() {}

// UnsafeCalendarServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CalendarServer will
// result in compilation errors.
type UnsafeCalendarServer interface {
	mustEmbedUnimplementedCalendarServer()
}

func RegisterCalendarServer(s grpc.ServiceRegistrar, srv CalendarServer) {
	s.RegisterService(&Calendar_ServiceDesc, srv)
}

func _Calendar_CreateEventV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventV1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarServer).CreateEventV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Calendar/CreateEventV1",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarServer).CreateEventV1(ctx, req.(*EventV1))
	}
	return interceptor(ctx, in, info, handler)
}

func _Calendar_UpdateEventV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventV1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarServer).UpdateEventV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Calendar/UpdateEventV1",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarServer).UpdateEventV1(ctx, req.(*EventV1))
	}
	return interceptor(ctx, in, info, handler)
}

func _Calendar_DeleteEventV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventIdV1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarServer).DeleteEventV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Calendar/DeleteEventV1",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarServer).DeleteEventV1(ctx, req.(*EventIdV1))
	}
	return interceptor(ctx, in, info, handler)
}

func _Calendar_ListEventsDayV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventListRequestV1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarServer).ListEventsDayV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Calendar/ListEventsDayV1",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarServer).ListEventsDayV1(ctx, req.(*EventListRequestV1))
	}
	return interceptor(ctx, in, info, handler)
}

func _Calendar_ListEventsWeekV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventListRequestV1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarServer).ListEventsWeekV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Calendar/ListEventsWeekV1",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarServer).ListEventsWeekV1(ctx, req.(*EventListRequestV1))
	}
	return interceptor(ctx, in, info, handler)
}

func _Calendar_ListEventsMonthV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventListRequestV1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarServer).ListEventsMonthV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Calendar/ListEventsMonthV1",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarServer).ListEventsMonthV1(ctx, req.(*EventListRequestV1))
	}
	return interceptor(ctx, in, info, handler)
}

// Calendar_ServiceDesc is the grpc.ServiceDesc for Calendar service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Calendar_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Calendar",
	HandlerType: (*CalendarServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateEventV1",
			Handler:    _Calendar_CreateEventV1_Handler,
		},
		{
			MethodName: "UpdateEventV1",
			Handler:    _Calendar_UpdateEventV1_Handler,
		},
		{
			MethodName: "DeleteEventV1",
			Handler:    _Calendar_DeleteEventV1_Handler,
		},
		{
			MethodName: "ListEventsDayV1",
			Handler:    _Calendar_ListEventsDayV1_Handler,
		},
		{
			MethodName: "ListEventsWeekV1",
			Handler:    _Calendar_ListEventsWeekV1_Handler,
		},
		{
			MethodName: "ListEventsMonthV1",
			Handler:    _Calendar_ListEventsMonthV1_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "EventService.proto",
}
