version: '3.8'

services:
  scheduler:
    image: calendar-scheduler:develop
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    deploy:
      mode: global
      replicas: 1
    volumes:
      - ../configs/scheduler_intgr_config.yaml:/etc/config.yaml:ro
    networks:
      - app

  tests:
    image: golang:1.19-alpine
    working_dir: /app
    command: sh -c 'go test -v ./tests/...'
    environment:
      CGO_ENABLED: 0
    depends_on:
      calendar:
        condition: service_healthy
      scheduler:
        condition: service_started
      sender:
        condition: service_started
    volumes:
      - ./../:/app/
      - ../configs/intgr_config.yaml:/etc/config.yaml:ro
    networks:
      - app

networks:
  app:
