logger:
  level: DEBUG
http:
  host: 0.0.0.0
  port: 82
grpc:
  host: 0.0.0.0
  port: 81
database:
  dsn: "host=postgres port=5432 user=calendar_user password=calendar_pass dbname=calendar sslmode=disable"
storage:
  driver: "postgres" # memory
