logger:
  level: DEBUG
server:
  host: 0.0.0.0
  port: 80
database:
  dns: "host=postgres port=5432 user=calendar_user password=calendar_pass dbname=calendar sslmode=disable"
storage:
  driver: "memory" # postgres